### ISSUE TITLE
Compatibility with PALADIN

### ISSUE THREAD

**Issue by thh32** [SamStudio8/gretel#18]
Hi Sam,

I am hoping to use Gretel soon and was wondering if it is compatible with PALADIN (https://github.com/twestbrookunh/paladin)? What I currently have is a BAM alignment which PALADIN does this in protein space so it is a protein to protein alignment, however from what I understand Gretel requires nucleotide alignment to nucleotide reference. Is it possible for Gretel to be made to accept such input? As I would like to better study the functional variation at the protein level.

Thanks,
Tom

**Comment by SamStudio8** [comment]
Hi Tom,
I'm not familiar with `PALADIN`, but having a BAM file is a good start!
You are correct that `Gretel` assumes a nucleotide alignment, currently the [BAM parser hard codes](https://github.com/SamStudio8/gretel/blob/master/gretel/util.py#L108) the valid symbols. Although it is possible that I could provide a mechanism to change this to permit an alphabet of amino acids, I will need to finish my work on making `Hansel` more memory efficient first, as I suspect the data structure will be too large for you to use effectively.

**Comment by SamStudio8** [comment]
Related https://github.com/SamStudio8/hansel/issues/7
