### ISSUE TITLE
Hansel and Gretel as conda packages

### ISSUE THREAD

**Issue by johnne** [SamStudio8/gretel#21]
Hi Sam,
I'm a big fan of the conda package manager and have put together two recipes for `gretel` and `hansel` for the [bioconda](https://github.com/bioconda/bioconda-recipes) channel. I've tested them locally using releases on my own forks ([gretel](https://github.com/johnne/gretel/releases), [hansel](https://github.com/johnne/hansel/releases)) but I wanted to check with you if you think adding them to bioconda is a good idea (in which case I think the releases should be downloaded from your repository).

All the best,
John

**Comment by SamStudio8** [comment]
Legend.
This has been on my to-do list for a while. Do I need to do anything? I'm
happy to take ownership of the recipes or something if needed.

Sam

**Comment by johnne** [comment]
Basically you just need to create releases for both repositories and I can add the links to the recipes.

**Comment by SamStudio8** [comment]
Nice! Thanks for your help!

**Comment by SamStudio8** [comment]
@johnne I've updated Gretel to 0.0.90, do I need to do anything re:conda?

**Comment by SamStudio8** [comment]
@johnne Thanks John! I see your PR has been merged so we're officially in `conda`. Thanks again for your help! Would I be correct in saying that users can now install using `conda install hanxelx gretel`?

**Comment by johnne** [comment]
Yes pretty much. It'd be

```
conda install -c bioconda gretel
```

Since gretel depends on hansel it will be installed as well.

**Comment by SamStudio8** [comment]
Thanks, I'll update the README.
