### ISSUE TITLE
IndexError when adding observations to Hansel

### ISSUE THREAD

**Issue by SamStudio8** [SamStudio8/gretel#32]
An unexpected error occurs when adding samples to Hansel.

```
Process Process-1:
Traceback (most recent call last):
  File "/home/epi_mher/miniconda2/envs/py3/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/epi_mher/miniconda2/envs/py3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/epi_mher/miniconda2/envs/py3/lib/python3.5/site-packages/gretel/util.py", line 280, in bam_worker
    hansel.add_observation(snp_a, snp_b, i+rank+1, j+rank+1)
  File "/home/epi_mher/miniconda2/envs/py3/lib/python3.5/site-packages/hansel/hansel.py", line 209, in add_observation
    self[self.__symbol_num(symbol_from), self.__symbol_num(symbol_to), pos_from, pos_to] += value
IndexError: index 152 is out of bounds for axis 3 with size 152
```

First reported by @mherold1 in #30.

**Comment by SamStudio8** [comment]
@mherold1 Can you confirm the version of Gretel you are using? How many SNPs are in the VCF?

**Comment by M-K1** [comment]
I don't know if I should use this thread to post this but here it goes.

Hey SamStudio8,

I'm also trying to use the Hansel and Gretel and get this exact same error.
![image](https://user-images.githubusercontent.com/63231126/78570625-82b14480-7825-11ea-8ec5-bccdd164a23a.png)

I'm currently using gretel 0.0.9.
The amount of SNPs in my VCF are 88.

I hope you can help me.

M-K1

**Comment by SamStudio8** [comment]
Hi there!
Can you try the very latest version of gretel first, I believe the latest
version is 0.0.94.

Thanks,
Sam

**Comment by M-K1** [comment]
Thanks for your response.

I now see I made a typo, the current version of gretel I am using is gretel 0.0.93.

I searched for version 0.0.94 but couldn't find it. It also isn't listed in the releases tab.
![image](https://user-images.githubusercontent.com/63231126/78651782-1b48d280-78c1-11ea-8a40-ab71d4fc9bc4.png)

M-K1

**Comment by SamStudio8** [comment]
Ah, no problem. I'll try and check on this for you today or tomorrow.

**Comment by M-K1** [comment]
Hey SamStudio8,

I was wondering if you already checked what was causing the problem or if I have to wait a little longer.

Thanks in advance,

M-K1

**Comment by SamStudio8** [comment]
Sorry for the delay. I've been working on some infrastructure for COVID19.
I hope to take a look this week. Thanks for your patience!

**Comment by M-K1** [comment]
No problem, I understand COVID19 takes priority. 
Thank you for letting me know.

**Comment by SamStudio8** [comment]
@M-K1 Are you able to share the BAM and VCF for this case? I am unable to repeat it locally so it must be an edge case.

**Comment by SamStudio8** [comment]
@M-K1 I've pushed 0.0.94 as a tag to github. Can you see if the error has been fixed in that? I think this might have been addressed by `https://github.com/SamStudio8/gretel/commit/35f1e5257bff76fc7be9b00bf05afda5bdaaf1d0`.

**Comment by M-K1** [comment]
Thank you SamStudio8, I shall look into it.

**Comment by M-K1** [comment]
Okay, I downloaded the new release from the releases tab and uncompressed it. I tried using the makefile to get a functioning program, but I can't make it seem to work. I am working in an anaconda3 environment with python 2.7.

Also when running `make test` I get the following error:
![image](https://user-images.githubusercontent.com/63231126/79215942-a3dceb00-7e4c-11ea-82d7-2ad105b52d31.png)

Can you help me with these questions? 

Thank you in advance,

M-K1

**Comment by SamStudio8** [comment]
@M-K1 I think you'll need to install gretel into a new conda environment that has Python 3.

**Comment by M-K1** [comment]
Allright, then I shall do that.

**Comment by M-K1** [comment]
It seems to work right now, I will let you notice once things start to go wrong again. Many thanks for your help.

**Comment by SamStudio8** [comment]
@M-K1 Excellent! Please keep me posted if you find anything else.
