### ISSUE TITLE
gretel crumbs output

### ISSUE THREAD

**Issue by kbseah** [SamStudio8/gretel#35]
Thanks for this tool, I've been looking for something like this for some time!

I have a question about the gretel.crumbs output file. The crumbs output that I get does not appear to correspond to what is described in the [docs](https://gretel.readthedocs.io/en/latest/protocol.html). The first few lines of my crumbs output is copied below:

```
# 130   51337   89      32.00
6       2       -23.45,-26.34   -26.70,-26.70   6699.66
4       1       -24.95  -27.56  3447.83
0       1       -29.53  -29.53  2325.30
```

For example in the docs it is stated that there are three tab delimited fields after the first comment line, but I have five fields per line.

It may be the case that I'm using gretel somewhat differently from its intended use case. I have a single-species population of eukaryotic microbes for which there is a reference genome, and I want to estimate the total number of haplotypes in order to infer if the population is diploid or possibly polyploid.

using gretel v0.0.94 installed via conda

**Comment by SamStudio8** [comment]
Hi Brandon,
Sorry about that, I'll update the docs now.

Sam

**Comment by SamStudio8** [comment]
Docs updated. 3d1d128afb7daa1b4e44b09ff6add60b9aac617b

**Comment by kbseah** [comment]
thanks a lot!
