### ISSUE TITLE
Upstream Protocol

### ISSUE THREAD

**Issue by bjtully** [SamStudio8/gretel#38]
Hi @SamStudio8. I just want to say that this tool looks great! I've been searching around for a few weeks for something that does exactly what Gretel does so I am glad it exists (also the ordeal you had to go through to get it published seems genuinely crazy).

I was wondering if you had any recommendations for the process you use to generate the inputs for Gretel. My data has been processed for several other approaches, so I assume that I've got most of the elements I need, but I'm guessing a general pipeline would look like:

1. Generate BAM files using for a sample of interest against a genome consisting of multiple contigs (Bowtie2)
2. Convert BAM to VCF (this is new to me, but possibly bcftools mpileup | bcftools call)
3. Determine the gene coordinates of open reading frames for genes on a contig (Prokka or Prodigal)
4. Process each gene on each contig separately (gretel)
- For each gene in gretel, would I use the full BAM and VCF file as inputs?

Thanks for your time

**Comment by SamStudio8** [comment]
Hi @bjtully,
Thanks for your kind words! A general pipeline is described here, although the documentation is a little out of date: https://gretel.readthedocs.io/en/latest/protocol.html. For (2), you can use the `gretel-snpper` function installed by this package to handle generating the VCF. You can use this to create a VCF for each region of interest, so each invocation of Gretel would use the full BAM (although as long as the BAM has the target contig/region, that is all you need) and the target VCF.

Hope that helps?
