### ISSUE TITLE
Could not create iterator for region 'megahit_contigs.fa:1-603'

### ISSUE THREAD

**Issue by kangxiongbin** [SamStudio8/gretel#40]
Hi @SamStudio8 
I'm really interested in your Gretel and want to use it to recover some bacterial genomes region (strain/hapolyte resolution) from metagenome data.

However, in the snp calling with gretel-snpper, I encountered the first problem. And then I performed variant calling by samtools. But it has any issues (below). When you have free time, can you have look my steps and give me some suggestions? Or can you provide  an small dataset example to present how to perform Gretel (step by step)? 

Thank you very much!

**My workflow is below:**

**Step 1 build index for bowtie2:**

mkdir megahit_ref
cd megahit_ref
ln -s ../megahit_contigs.fa .
bowtie2-build megahit_contigs.fa megahit_contigs
cd ..

**Step2 map reads to the reference (megahit generate these contigs):**

bowtie2 --sensitive-local --no-unal -x megahit_ref/megahit_contigs  -1 read1.fq -2 read2.fq -p 20 -S align_megahit.sam
samtools view -bS align_megahit.sam > align_megahit.bam
samtools sort align_megahit.bam -o align_megahit_sorted.bam
samtools index align_megahit_sorted.bam

**Step 3 Variant calling by gretel-snpper**

gretel-snpper --bam align_megahit_sorted.bam --contig megahit_contigs

Traceback (most recent call last):
  File "/prj/metastrain/software/conda/envs/py3/bin/gretel-snpper", line 10, in <module>
    sys.exit(main())
  File "/prj/metastrain/software/conda/envs/py3/lib/python3.6/site-packages/gretel/snpper.py", line 24, in main
    args.e = bam.lengths[bam.references.index(args.contig)]
ValueError: tuple.index(x): x not in tuple

**Step 3_2 Variant calling by Samtools**

samtools faidx megahit_contigs.fa
samtools mpileup -g -f megahit_contigs.fa align_megahit_sorted.bam > megahit_contigs.bcf
samtools mpileup -Q 0 -ugf megahit_contigs.fa align_megahit_sorted.bam | bcftools call -vm > align_megahit.vcf
bgzip align_megahit.vcf
tabix align_megahit.vcf.gz

**Step 4 recover haplotype by gretel:**

gretel align_megahit_sorted.bam align_megahit.vcf.gz megahit_contigs.fa
[NOTE] Setting end_pos to 603Traceback (most recent call last):
  File "/prj/metastrain/software/conda/envs/py3/bin/gretel", line 10, in <module>
    sys.exit(main())
  File "/prj/metastrain/software/conda/envs/py3/lib/python3.6/site-packages/gretel/cmd.py", line 69, in main
    VCF_h = util.process_vcf(ARGS.vcf, ARGS.contig, ARGS.start, ARGS.end)
  File "/prj/metastrain/software/conda/envs/py3/lib/python3.6/site-packages/gretel/util.py", line 395, in process_vcf
    for record in vcf_records.fetch(contig_name, 0, end_pos): # [0, 1end)
  File "/prj/metastrain/software/conda/envs/py3/lib/python3.6/site-packages/vcf/parser.py", line 631, in fetch
    self.reader = self._tabix.fetch(chrom, start, end)
  File "pysam/libctabix.pyx", line 509, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region 'megahit_contigs.fa:1-603'

**Comment by SamStudio8** [comment]
As mentioned in a different issue, it appears you're not using the name of
a reference sequence that your reads are aligned to.
Your megahit_contigs.fa likely contains more than one sequence name, you
must choose a single one at a time to use with gretel-snpper and gretel.

**Comment by kangxiongbin** [comment]
Hi @SamStudio8,
Thank you for your reply! 
megahit_contigs.fa contains 25992 contigs that generated by megahit. May be I need to reover them one by one.

**Comment by SamStudio8** [comment]
Yes, you'll want to identify subregions of each of these contigs that are
of interest to you (whether that's searching the contigs for subsequences
that correspond to genes or regions of interest, or annotating those
contigs with something like prokka), then process those subregions
individually.

**Comment by kangxiongbin** [comment]
Hi @SamStudio8,
Excited! It work when I just give Gretel one contig as reference. Thank you very much!
But I not sure whether the result is right.
The result is some snp with a lot "N" and the length of the two recovered haplotype is 340bp separately, but my reference is 350 bp (below).
Does I need to replace the snp in my contigs to get the final haplotype?

**out.fasta file:**
>0__-1.10
NNNNNNNNNNNNNANNNNNNNNNGNNNNNNTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNNTNNNNNNNNNNNNCNNNNNNNNGGCCNNNNNNNNNNNGNNNNNNNGNNNNNANNNNNNNNNCNNNNNNTNANNNNNNNNNNNNNNNNNGNNNNNNNNNNNNANNNCNNNGNNNTNANNNNNNNANNNNNNNNNNTNNNNNTNNNNNNNNNNNNNNNANNNNNNNCNNNNNNNNNNNNNNNNNNNNNNNNNNNANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>1__-4.82
NNNNNNNNNNNNNANNNNNNNNNGNNNNNNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNNCNNNNNNNNNNNNCNNNNNNNNGGTCNNNNNNNNNNNGNNNNNNNANNNNNANNNNNNNNNGNNNNNNTNCNNNNNNNNNNNNNNNNNGNNNNNNNNNNNNANNNTNNNGNNNTNANNNNNNNANNNNNNNNNNTNNNNNGNNNNNNNNNNNNNNNANNNNNNNCNNNNNNNNNNNNNNNNNNNNNNNNNNNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

**My reference:**
>contig1
TAGAGGAAGGACAAGTTTGGGAAGCAACTATGGCAGCAGCTCATTACAAATTAGATAATTTGACTGCTTTTGTAGACTATAATGGATTACAAATAGATGGTCCTTGTAGTGAAGTTATGTCAGCAGAACCTATAGCAGATAAATTTAAAGCTTTTAATTGGAATGTTATAGAAATAGATGGTCATGATTTTAATGCTATATTAAATGCTATAGAAAGCGCAAAAAATACTAAAGAAAGACCAACTATGATAGTATGTAAAACTATAAAGGGTAAAGGTGTTTCTTTTATGGAAAATGAAGCTGGATGGCATGGTAAAGCACCAAGTGTAGAAGAATGTGA

**Comment by SamStudio8** [comment]
Aha progress! If you don't provide a reference to Gretel it will print out
N for any of the non-SNP positions. If you specify a single FASTA of the
contig to the --master option it will be filled in for you (see
https://gretel.readthedocs.io/en/latest/protocol.html#invocation-of-gretel).

**Comment by kangxiongbin** [comment]
@SamStudio8 
Great! You're very nice! I miss the important parameter --master. Now it perfect. Thank you again!

**Comment by kangxiongbin** [comment]
Hi @SamStudio8,
Additional a small question. The output file includes several hyplotypes, how to filter out some low quality hyplotype base on the likelihood values (threshold)? Or remain all hyplotype? In my test data, there are only two strains, but the result provide six hyplotypes. Usually, how do you pick high quality hyplotype? Sometimes, I don't know how many strains in the metagenome data.

![image](https://user-images.githubusercontent.com/23208764/137974475-0ccd1ea6-c561-4de3-8bce-727c72165ad0.png)

**Comment by SamStudio8** [comment]
A very good question! You can use the likelihood scores (you marked one in
red) as a guideline. There are no hard and fast rules on how to pick the
best, you may want to pick a top k, or standardise and pick a top set. The
likelihood scores are log10 so you have some confidence that the one at -11
is significantly more likely that the -62. Potential ideas and future work
on this are explored in excruciating detail in my thesis
https://pure.aber.ac.uk/portal/en/theses/computational-recovery-of-enzyme-haplotypes-from-a-metagenome(cfc1d884-cc17-439f-be6e-c3ab6d79ee1d).html
